
spring.datasource.url=jdbc:postgresql://localhost:5433/chatex_test
spring.datasource.username=testuser
spring.datasource.password=testpass
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.docker.compose.enabled=false

server.port=8081